### ISSUE TITLE
Please specify if people can put paid setups here. 

### ISSUE THREAD

**Issue by ConJaBst** [Lon3035/ACC_Setups#5]
As much as I hate the whole paid setup marketplace, it wont be fair to them if all their setups are publicly available.

**Comment by Lon3035** [comment]
You are right, ill add a section into the readme.

**Comment by Lon3035** [comment]
Added following line under Contributions/Rules
> Please do not add paid setups, it would not be fair to publish them

I also try not to accept paid setups, but it could be hard to identify them.
If you notice some, please report them as an issue.
